package com.revature.daos;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import com.revature.models.Product;
import com.revature.util.ConnectionUtil;

public class ProductPostgres implements ProductDAO {

	@Override
	public Product createProduct(Product p) {
		String sql = "insert into products (product_name, price) values (?,?) returning id;";
		try(Connection c = ConnectionUtil.getConnectionFromFile()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setString(1, p.getProduct_name());
			ps.setDouble(2, p.getPrice());
			
			ResultSet rs = ps.executeQuery(); // return the id generated by the database
			if(rs.next()) {
				p.setId(rs.getInt("id"));
			}
			
		} catch (SQLException | IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return p;
	}

	@Override
	public Product retrieveProductById(int id) {
		String sql = "select * from products where id = ?";
		Product product = null;
		try(Connection c = ConnectionUtil.getConnectionFromFile()) {
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setInt(1, id);
			
			ResultSet rs = ps.executeQuery();
			if(rs.next()) {
				product = new Product();
				product.setProduct_name(rs.getString("product_name"));
				product.setPrice(rs.getDouble("price"));
				product.setOffer_price(rs.getDouble("offer_price"));
				product.setPaid(rs.getDouble("paid"));
				product.setPaidDate(rs.getDate("paid_date").toLocalDate());
				product.setUser_id(rs.getInt("user_id"));
				
			}
		} catch (Exception e) {
			// TODO: handle exception
		}
		return null;
	}

	@Override
	public List<Product> retrieveProducts() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean updateProduct(Product p) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean deleteProductById(int id) {
		// TODO Auto-generated method stub
		return false;
	}

}
